version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - "db"

  db:
    image: mysql:8.0
    container_name: godockerDB
    env_file: .env
    environment:
      MYSQL_DATABASE: test_go
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Vahak@123
      MYSQL_PASSWORD: Vahak@123
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3307:3307
    security_opt:
      - seccomp:unconfined

volumes:
  db-data:
    driver: local